spring.application.name: dummy-library

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dummy_library_db
    username: postgres
    password: pwd
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 300000
      minimum-idle: 5
  flyway:
    enabled: false
  jpa:
    hibernate.ddl-auto: create
    defer-datasource-initialization: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: always
  kafka:
    consumer:
      auto-offset-reset: earliest
      max-poll-records: 1
      bootstrap-servers: localhost:9092
      group-id: group-id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            use:
              type:
                headers: false
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


