version: '3'
services:
  postgresql:
    image: postgres:12
    command: postgres -c 'max_connections=250'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: postgres
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 11050:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
  kafka:
    image: bitnami/kafka:latest
    tty: true
    stdin_open: true
    ports:
      - 9092:9092
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CFG_LISTENERS: "CLIENT://:9092,EXTERNAL://:11051"
      KAFKA_CFG_ADVERTISED_LISTENERS: "CLIENT://localhost:9092,EXTERNAL://localhost:11051"
      KAFKA_INTER_BROKER_LISTENER_NAME: "CLIENT"
      KAFKA_CFG_BROKER_ID: 1
    depends_on:
      - zookeeper